version: "3.9"

services:
  api:
    build: .
    container_name: rog_ingestion_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data/incoming:/app/data/incoming
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17
    container_name: rog_ingestion_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rog_ingestion
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: rog_ingestion_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
